### ISSUE TITLE
Permissions issue not fixed in Preview branch

### ISSUE THREAD

**Issue by lavavex** [Suwayomi/docker-tachidesk#48]
The issues presented in #22 has not been fixed in preview, issue still occurs due to hard coded user and group ids 1000:1000
can we just grab the current user and group ids on startup and use those instead?

**Comment by rashad2985** [comment]
I resolved the issue on my self hosted instance without needing to switch to the `:develop` branch or tackling with users, just staying on the `:stable` branch as follows:
Instead of mounting the full path `/home/suwayomi/.local/share/Tachidesk` just mount the user home path `/home/suwayomi`, thats it!

**Comment by ravenspeak** [comment]
I can't get this to work even when using the develop tag. I tried running it through docker compose and also docker run directly but I'm always getting permissions denied issue.

**Comment by Syer10** [comment]
Should be fixed

**Comment by Yukaii** [comment]
Try with the latest `ghcr.io/suwayomi/tachidesk:v1.0.0-r1515` but still not working

**Comment by Yukaii** [comment]
Realized that I didn't create the data folder with current user permission. 😅

**Comment by Kickunio** [comment]
Ok, I tested the problem on the fresh instance and everything is OK. Maybe the clear cache button doesn't clear the cache all the way? Is there any other way to clear the cache?
